### ISSUE TITLE
Need special cases for some twiki formatting

### ISSUE THREAD

**Issue by jwakely** [rwdougla/wg21tools#1]
Twiki links like [[http://example.com][example]] get the "http" turned into "<font color=xxx>http</font>" which breaks the link.

Twiki titles starting with "---+" (and some extra number of pluses) get <br /> appended, which means they aren't recognized as headings.

I'll see if I can fix these, but I'm filing this so I don't forget.

**Comment by rwdougla** [comment]
I believe I have fixed this. Please let me know if you see further issues. As a drive-by, I also added a variety of common words to precede ':' in wg21 minutes, such as range, ranges, literals, group, several, many, std, and experimental. I'll increase that list as we see more instances

**Comment by jwakely** [comment]
The "---+ Title" case still gets `<br />` appended, which means twiki doesn't make it a heading.
